server:
  port: 8000
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Laundry
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # tạo bảng tự động theo Entity (hoặc validate / none)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect